### ISSUE TITLE
No module named utmpaccess

### ISSUE THREAD

**Issue by odessadraekavik** [FedericoCeratto/geoip-lastlog#1]
Hello there,

When I run geoip-lastlog, this happens : 
`import utmpaccess`
`ImportError: No module named utmpaccess`

Python 2.7.12
Ubuntu 16.04.1 LTS (Xenial Xerus)

Thanks

**Comment by odessadraekavik** [comment]
> sakarias@ODESSA-SRV:~$ ****sudo find / -name "_utmpaccess_"****
> /usr/lib/python2.7/dist-packages/utmpaccessmodule.x86_64-linux-gnu.so

**Comment by FedericoCeratto** [comment]
Hello @Sakarias-Longhorn , you need to install the https://pypi.python.org/pypi/utmp module.
On Debian and derivatives: `apt-get install python-utmp`

**Comment by odessadraekavik** [comment]
### **sudo apt install python-utmp**

Reading package lists... Done
Building dependency tree
Reading state information... Done

### **python-utmp is already the newest version (0.8.2).**

0 upgraded, 0 newly installed, 0 to remove and 60 not upgraded.
sakarias@ODESSA-SRV:~$ geoip-lastlog
Traceback (most recent call last):
  File "/usr/local/bin/geoip-lastlog", line 9, in <module>
    load_entry_point('geoip-lastlog==0.6', 'console_scripts', 'geoip-lastlog')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 2235, in resolve
    module = **import**(self.module_name, fromlist=['**name**'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/geoip_lastlog/**init**.py", line 13, in <module>
    import utmp
  File "/usr/lib/python2.7/dist-packages/utmp.py", line 1, in <module>
    import utmpaccess

### **ImportError: No module named utmpaccess**

**Comment by odessadraekavik** [comment]
Fixed by running : 

> sudo cp /usr/lib/python2.7/dist-packages/utmpaccessmodule.x86_64-linux-gnu.so /usr/lib/python2.7/dist-packages/utmpaccessmodule.so
